
<template>
<div class="loadingio-spinner-interwind-j3xakeyw7a"><div class="ldio-khx8cq1i9bq">
<div><div><div><div></div></div></div><div><div><div></div></div></div></div>
</div></div>
</template>

<script>
    export default {
    //name: 'Loader',
    }
</script>

<style type="text/css">
@keyframes ldio-khx8cq1i9bq-r {
  0%, 100% { animation-timing-function: cubic-bezier(0.2 0 0.8 0.8) }
  50% { animation-timing-function: cubic-bezier(0.2 0.2 0.8 1) }
  0% { transform: rotate(0deg) }
  50% { transform: rotate(180deg) }
  100% { transform: rotate(360deg) }
}
@keyframes ldio-khx8cq1i9bq-s {
  0%, 100% { animation-timing-function: cubic-bezier(0.2 0 0.8 0.8) }
  50% { animation-timing-function: cubic-bezier(0.2 0.2 0.8 1) }
  0% { transform: translate(-15px,-15px) scale(0) }
  50% { transform: translate(-15px,-15px) scale(1) }
  100% { transform: translate(-15px,-15px) scale(0) }
}
.ldio-khx8cq1i9bq > div { transform: translate(0px,-7.5px) }
.ldio-khx8cq1i9bq > div > div {
  animation: ldio-khx8cq1i9bq-r 0.625s linear infinite;
  transform-origin: 50px 50px;
}
.ldio-khx8cq1i9bq > div > div > div {
  position: absolute;
  transform: translate(50px, 41px);
}
.ldio-khx8cq1i9bq > div > div > div > div {
  width: 30px;
  height: 30px;
  border-radius: 50%;
  background: #fe718d;
  animation: ldio-khx8cq1i9bq-s 0.625s linear infinite;
}
.ldio-khx8cq1i9bq > div > div:last-child {
  animation-delay: -0.3125s;
}
.ldio-khx8cq1i9bq > div > div:last-child > div > div {
  animation-delay: -0.3125s;
  background: #46dff0;
}
.loadingio-spinner-interwind-j3xakeyw7a {
  width: 78px;
  height: 78px;
  display: inline-block;
  overflow: hidden;
  background: rgba(255, 255, 255, 0);
}
.ldio-khx8cq1i9bq {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.78);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-khx8cq1i9bq div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>